# Generated by Django 4.2.7 on 2023-12-22 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Janylyktar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/photo/%Y/%m/%d', verbose_name='изображение категории')),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Mugalim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(upload_to='media/photo/%Y/%m/%d', verbose_name='изображение категории')),
                ('login', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Okuuchular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(upload_to='media/photo/%Y/%m/%d', verbose_name='изображение категории')),
                ('login', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.class')),
            ],
        ),
        migrations.CreateModel(
            name='Posishenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('baa', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('mugalim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mugalim')),
                ('okuuchu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.okuuchular')),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('klass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.class')),
                ('mugalim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mugalim')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='mugalim',
            name='predmet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.predmet'),
        ),
        migrations.AddField(
            model_name='mugalim',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.roles'),
        ),
        migrations.AddField(
            model_name='janylyktar',
            name='mugalim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mugalim'),
        ),
        migrations.AddField(
            model_name='class',
            name='mugalim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mugalim'),
        ),
    ]
