# Generated by Django 4.2.7 on 2023-12-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_class_janylyktar_mugalim_okuuchular_posishenie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posishenie',
            name='predmet_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='website.predmet'),
        ),
    ]
