# Generated by Django 4.2.7 on 2023-12-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_posishenie_predmet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posishenie',
            name='predmet_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.predmet'),
        ),
    ]
